package controller

// Vendored from github.com/google/uuid v1.6.0 hash.go (BSD-3-Clause,
// Copyright 2016 Google Inc.). Only NewSHA1's path is taken; local diffs
// are marked. That module's LICENSE, verbatim:
//
// Copyright (c) 2009,2014 Google Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import (
	"crypto/sha1"
	"hash"
	"uuid"
)

// newHashUUID returns a new UUID derived from the hash of space concatenated
// with data generated by h. The hash should be at least 16 byte in length.
// The first 16 bytes of the hash are used to form the UUID. The version of
// the UUID will be the lower 4 bits of version.
func newHashUUID(h hash.Hash, space uuid.UUID, data []byte, version int) uuid.UUID { // local diff: std uuid type, unexported
	h.Reset()
	h.Write(space[:]) //nolint:errcheck
	h.Write(data)     //nolint:errcheck
	s := h.Sum(nil)
	var u uuid.UUID // local diff: named u, not uuid -- the std package holds that name here
	copy(u[:], s)
	u[6] = (u[6] & 0x0f) | uint8((version&0xf)<<4)
	u[8] = (u[8] & 0x3f) | 0x80 // RFC 4122 variant
	return u
}

// newSHA1UUID returns a new SHA1 (Version 5) UUID based on the
// supplied name space and data.
func newSHA1UUID(space uuid.UUID, data []byte) uuid.UUID {
	return newHashUUID(sha1.New(), space, data, 5)
}
